apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongod.conf: |
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: 32
        collectionConfig:
          blockCompressor: zstd
    net:
      port: 27017
      bindIp: 0.0.0.0
    replication:
      replSetName: rs0
    sharding:
      clusterRole: shardsvr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard1
spec:
  serviceName: mongo-shard1
  replicas: 3
  selector:
    matchLabels:
      app: mongo-shard1
  template:
    metadata:
      labels:
        app: mongo-shard1
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command: ["mongod", "--config", "/etc/mongod.conf"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            memory: "64Gi"
            cpu: "8"
          limits:
            memory: "64Gi"
            cpu: "16"
      volumes:
      - name: config
        configMap:
          name: mongo-config
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 4Ti
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1
spec:
  clusterIP: None
  selector:
    app: mongo-shard1
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard2
spec:
  serviceName: mongo-shard2
  replicas: 3
  selector:
    matchLabels:
      app: mongo-shard2
  template:
    metadata:
      labels:
        app: mongo-shard2
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command: ["mongod", "--config", "/etc/mongod.conf"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            memory: "64Gi"
            cpu: "8"
          limits:
            memory: "64Gi"
            cpu: "16"
      volumes:
      - name: config
        configMap:
          name: mongo-config
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 4Ti
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2
spec:
  clusterIP: None
  selector:
    app: mongo-shard2
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard3
spec:
  serviceName: mongo-shard3
  replicas: 3
  selector:
    matchLabels:
      app: mongo-shard3
  template:
    metadata:
      labels:
        app: mongo-shard3
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command: ["mongod", "--config", "/etc/mongod.conf"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: config
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        resources:
          requests:
            memory: "64Gi"
            cpu: "8"
          limits:
            memory: "64Gi"
            cpu: "16"
      volumes:
      - name: config
        configMap:
          name: mongo-config
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: fast-ssd
      resources:
        requests:
          storage: 4Ti
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard3
spec:
  clusterIP: None
  selector:
    app: mongo-shard3
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-config
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-config
  template:
    metadata:
      labels:
        app: mongo-config
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019"]
        ports:
        - containerPort: 27019
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-config
spec:
  selector:
    app: mongo-config
  ports:
  - port: 27019
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:7.0
        command: ["mongos", "--configdb", "configReplSet/mongo-config:27019", "--port", "27017"]
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
spec:
  selector:
    app: mongos
  ports:
  - port: 27017
    targetPort: 27017