apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infinite-ai-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/infinite-ai-security.git
    targetRevision: main
    path: gitops/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-hub
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
